name: Next.js App CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'nextjs-app/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd nextjs-app/swcotd
          npm install

      - name: Run tests
        run: |
          cd nextjs-app/swcotd
          npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: nextjs-app/swcotd
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-nextjs-app:latest